language: elixir

otp_release:
  - 18.0

elixir:
  - 1.1.0
  - 1.1.1
  - 1.2.0
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.2.4
  - 1.2.5
  - 1.2.6
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - 1.4.0

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0152272011bece7f993c
    on_success: change
    on_failure: always
    on_start: false


after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
